sudo: required
dist: bionic
language: python
services:
  - docker
python:
  - "3.9"
before_install:
  - build_scripts/travis_singularity.sh
  - pip install flake8 pytest pytest-cov pytest-flake8 python-coveralls
script:
  - build_scripts/travis_tests.sh
